import dotenv from 'dotenv';

dotenv.config();

interface EnvConfig {
  // AI APIs
  AI_API_URL: string;
  AI_API_CONTENT_TYPE: string;
  AI_API_MODEL: string;
  AI_API_STREAM: string;
  AI_TIMEOUT_MS: string;
  AI_RETRY_ATTEMPTS: string;
  ANTHROPIC_API_KEY?: string;
  ANTHROPIC_MODEL: string;
  ANTHROPIC_MAX_TOKENS: string;
  GROK_API_KEY?: string;
  GROK_API_URL?: string;
  GROK_MODEL: string;
  GROK_MAX_TOKENS: string;

  // Database
  DATABASE_URL: string;

  // Owner
  OWNER_WHATSAPP?: string;
  OWNER_TELEGRAM_ID?: string;
  OWNER_NAME?: string;

  // Telegram
  TELEGRAM_BOT_TOKEN?: string;
  TELEGRAM_ENABLED: string;
  WHATSAPP_ENABLED: string;
  WHATSAPP_AUTH_DIR: string;

  // Twitter
  TWITTER_ENABLED: string;
  TWITTER_AUTH_TOKEN?: string;
  TWITTER_CT0?: string;
  TWITTER_USERNAME?: string;
  TWITTER_HEADLESS: string;
  TWITTER_COOKIES_PATH: string;
  TWITTER_AUTONOMOUS_ENABLED: string;

  // Behavior
  STUDY_INTERVAL_MIN?: string;
  STUDY_AUTONOMOUS_ENABLED: string;
  POST_INTERVAL_MIN?: string;
  MENTIONS_CHECK_MIN?: string;
  SELF_IMPROVEMENT_ENABLED: string;
  SELF_IMPROVEMENT_MAX_FILES: string;
  SELF_IMPROVEMENT_MAX_SUGGESTIONS: string;
  ANALYTICS_AUTONOMOUS_ENABLED: string;
  ANALYTICS_INTERVAL_MIN: string;
  OLLAMA_MIN_INTERVAL_MS: string;
  ANTHROPIC_MIN_INTERVAL_MS: string;
  GROK_MIN_INTERVAL_MS: string;
  TWITTER_API_MIN_INTERVAL_MS: string;
  HEALTHCHECK_ENABLED: string;
  HEALTHCHECK_INTERVAL_MIN: string;
  MAINTENANCE_ENABLED: string;
  BACKUP_ENABLED: string;
  BACKUP_INTERVAL_HOURS: string;
  BACKUP_DIR: string;
  BACKUP_RETENTION_DAYS: string;
  CLEANUP_ENABLED: string;
  CLEANUP_INTERVAL_HOURS: string;
  CLEANUP_TRAINING_RETENTION_DAYS: string;
  CLEANUP_QUALITY_THRESHOLD: string;
  HIVE_ENABLED: string;
  HIVE_BIND_HOST: string;
  HIVE_PORT: string;
  HIVE_AGENT_NAME: string;
  HIVE_AGENT_ROLE: string;
  HIVE_SHARED_TOKEN: string;
  HIVE_PEERS_JSON: string;
  HIVE_REQUEST_TIMEOUT_MS: string;

  // v1.2 — Tools + Agent Loop
  FORCE_LOCAL: string;
  AGENT_LOOP_MAX_ROUNDS: string;
  TOOL_BASH_ENABLED: string;
  TOOL_WEB_ENABLED: string;
  TOOL_SSH_ENABLED: string;
  WEB_CACHE_TTL_SECONDS: string;

  // v1.2 — Auto Git Backup
  GIT_AUTO_BACKUP_ENABLED: string;
  GIT_PUSH_ENABLED: string;
  GIT_REMOTE: string;

  // v1.2 — Memory Consolidation
  MEMORY_CONSOLIDATION_ENABLED: string;
  MEMORY_CONSOLIDATION_INTERVAL_HOURS: string;
  MEMORY_MIN_QUALITY_SCORE: string;

  // Environment
  NODE_ENV: string;
  LOG_LEVEL: string;
}

const getEnv = (key: keyof EnvConfig, defaultValue?: string, required: boolean = false): string => {
  const value = process.env[key] || defaultValue;
  if (!value && required) {
    throw new Error(`Missing required environment variable: ${key}`);
  }
  return value || '';
};

export const env: EnvConfig = {
  // AI APIs
  AI_API_URL: getEnv('AI_API_URL', '', true),
  AI_API_CONTENT_TYPE: getEnv('AI_API_CONTENT_TYPE', 'application/json'),
  AI_API_MODEL: getEnv('AI_API_MODEL', 'llama3.2:3b'),
  AI_API_STREAM: getEnv('AI_API_STREAM', 'false'),
  AI_TIMEOUT_MS: getEnv('AI_TIMEOUT_MS', '30000'),
  AI_RETRY_ATTEMPTS: getEnv('AI_RETRY_ATTEMPTS', '3'),
  ANTHROPIC_API_KEY: getEnv('ANTHROPIC_API_KEY', ''),
  ANTHROPIC_MODEL: getEnv('ANTHROPIC_MODEL', 'claude-3-5-sonnet-latest'),
  ANTHROPIC_MAX_TOKENS: getEnv('ANTHROPIC_MAX_TOKENS', '1024'),
  GROK_API_KEY: getEnv('GROK_API_KEY', ''),
  GROK_API_URL: getEnv('GROK_API_URL', ''),
  GROK_MODEL: getEnv('GROK_MODEL', 'grok-2'),
  GROK_MAX_TOKENS: getEnv('GROK_MAX_TOKENS', '1024'),

  // Database
  DATABASE_URL: getEnv('DATABASE_URL', '', true),

  // Owner
  OWNER_WHATSAPP: getEnv('OWNER_WHATSAPP', ''),
  OWNER_TELEGRAM_ID: getEnv('OWNER_TELEGRAM_ID', ''),
  OWNER_NAME: getEnv('OWNER_NAME', 'Owner'),

  // Telegram
  TELEGRAM_BOT_TOKEN: getEnv('TELEGRAM_BOT_TOKEN', ''),
  TELEGRAM_ENABLED: getEnv('TELEGRAM_ENABLED', 'false'),
  WHATSAPP_ENABLED: getEnv('WHATSAPP_ENABLED', 'false'),
  WHATSAPP_AUTH_DIR: getEnv('WHATSAPP_AUTH_DIR', 'data/whatsapp-auth'),

  // Twitter
  TWITTER_ENABLED: getEnv('TWITTER_ENABLED', 'false'),
  TWITTER_AUTH_TOKEN: getEnv('TWITTER_AUTH_TOKEN', ''),
  TWITTER_CT0: getEnv('TWITTER_CT0', ''),
  TWITTER_USERNAME: getEnv('TWITTER_USERNAME', ''),
  TWITTER_HEADLESS: getEnv('TWITTER_HEADLESS', 'true'),
  TWITTER_COOKIES_PATH: getEnv('TWITTER_COOKIES_PATH', 'data/twitter/cookies.json'),
  TWITTER_AUTONOMOUS_ENABLED: getEnv('TWITTER_AUTONOMOUS_ENABLED', 'false'),

  // Behavior
  STUDY_INTERVAL_MIN: getEnv('STUDY_INTERVAL_MIN', '30'),
  STUDY_AUTONOMOUS_ENABLED: getEnv('STUDY_AUTONOMOUS_ENABLED', 'false'),
  POST_INTERVAL_MIN: getEnv('POST_INTERVAL_MIN', '120'),
  MENTIONS_CHECK_MIN: getEnv('MENTIONS_CHECK_MIN', '60'),
  SELF_IMPROVEMENT_ENABLED: getEnv('SELF_IMPROVEMENT_ENABLED', 'false'),
  SELF_IMPROVEMENT_MAX_FILES: getEnv('SELF_IMPROVEMENT_MAX_FILES', '20'),
  SELF_IMPROVEMENT_MAX_SUGGESTIONS: getEnv('SELF_IMPROVEMENT_MAX_SUGGESTIONS', '3'),
  ANALYTICS_AUTONOMOUS_ENABLED: getEnv('ANALYTICS_AUTONOMOUS_ENABLED', 'false'),
  ANALYTICS_INTERVAL_MIN: getEnv('ANALYTICS_INTERVAL_MIN', '180'),
  OLLAMA_MIN_INTERVAL_MS: getEnv('OLLAMA_MIN_INTERVAL_MS', '200'),
  ANTHROPIC_MIN_INTERVAL_MS: getEnv('ANTHROPIC_MIN_INTERVAL_MS', '500'),
  GROK_MIN_INTERVAL_MS: getEnv('GROK_MIN_INTERVAL_MS', '500'),
  TWITTER_API_MIN_INTERVAL_MS: getEnv('TWITTER_API_MIN_INTERVAL_MS', '1200'),
  HEALTHCHECK_ENABLED: getEnv('HEALTHCHECK_ENABLED', 'true'),
  HEALTHCHECK_INTERVAL_MIN: getEnv('HEALTHCHECK_INTERVAL_MIN', '5'),
  MAINTENANCE_ENABLED: getEnv('MAINTENANCE_ENABLED', 'true'),
  BACKUP_ENABLED: getEnv('BACKUP_ENABLED', 'false'),
  BACKUP_INTERVAL_HOURS: getEnv('BACKUP_INTERVAL_HOURS', '24'),
  BACKUP_DIR: getEnv('BACKUP_DIR', 'data/backups'),
  BACKUP_RETENTION_DAYS: getEnv('BACKUP_RETENTION_DAYS', '14'),
  CLEANUP_ENABLED: getEnv('CLEANUP_ENABLED', 'true'),
  CLEANUP_INTERVAL_HOURS: getEnv('CLEANUP_INTERVAL_HOURS', '12'),
  CLEANUP_TRAINING_RETENTION_DAYS: getEnv('CLEANUP_TRAINING_RETENTION_DAYS', '30'),
  CLEANUP_QUALITY_THRESHOLD: getEnv('CLEANUP_QUALITY_THRESHOLD', '0.45'),
  HIVE_ENABLED: getEnv('HIVE_ENABLED', 'false'),
  HIVE_BIND_HOST: getEnv('HIVE_BIND_HOST', '0.0.0.0'),
  HIVE_PORT: getEnv('HIVE_PORT', '8787'),
  HIVE_AGENT_NAME: getEnv('HIVE_AGENT_NAME', 'bolla-main'),
  HIVE_AGENT_ROLE: getEnv('HIVE_AGENT_ROLE', 'generalist'),
  HIVE_SHARED_TOKEN: getEnv('HIVE_SHARED_TOKEN', ''),
  HIVE_PEERS_JSON: getEnv('HIVE_PEERS_JSON', '[]'),
  HIVE_REQUEST_TIMEOUT_MS: getEnv('HIVE_REQUEST_TIMEOUT_MS', '45000'),

  // v1.2 — Tools + Agent Loop
  FORCE_LOCAL: getEnv('FORCE_LOCAL', 'false'),
  AGENT_LOOP_MAX_ROUNDS: getEnv('AGENT_LOOP_MAX_ROUNDS', '10'),
  TOOL_BASH_ENABLED: getEnv('TOOL_BASH_ENABLED', 'true'),
  TOOL_WEB_ENABLED: getEnv('TOOL_WEB_ENABLED', 'true'),
  TOOL_SSH_ENABLED: getEnv('TOOL_SSH_ENABLED', 'false'),
  WEB_CACHE_TTL_SECONDS: getEnv('WEB_CACHE_TTL_SECONDS', '3600'),

  // v1.2 — Auto Git Backup
  GIT_AUTO_BACKUP_ENABLED: getEnv('GIT_AUTO_BACKUP_ENABLED', 'true'),
  GIT_PUSH_ENABLED: getEnv('GIT_PUSH_ENABLED', 'false'),
  GIT_REMOTE: getEnv('GIT_REMOTE', 'origin'),

  // v1.2 — Memory Consolidation
  MEMORY_CONSOLIDATION_ENABLED: getEnv('MEMORY_CONSOLIDATION_ENABLED', 'false'),
  MEMORY_CONSOLIDATION_INTERVAL_HOURS: getEnv('MEMORY_CONSOLIDATION_INTERVAL_HOURS', '24'),
  MEMORY_MIN_QUALITY_SCORE: getEnv('MEMORY_MIN_QUALITY_SCORE', '0.2'),

  // Environment
  NODE_ENV: getEnv('NODE_ENV', 'development'),
  LOG_LEVEL: getEnv('LOG_LEVEL', 'info')
};
